name: Link ClickUp Task from PR Title

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Extract ClickUp IDs and update PR description
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        CLICKUP_IDS=$(echo grep -oP '\[\K[a-zA-Z0-9]+(?=\])')


      env:
        GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
