name: Update PR Description

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Check PR title and update description
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        if [[ "$PR_TITLE" == "Merge staging into main" ]]; then
          # Get all PRs merged into staging
          PRS=$(gh pr list --base staging --state merged --json title,url)

          # Start building the PR list
          PR_LIST="### PRs Merged into Staging:\n"

          # Extract the title and URL from each PR and format them
          for row in $(echo "$PRS" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            PR_TITLE=$(_jq '.title')
            PR_URL=$(_jq '.url')
            PR_LIST+="- [${PR_TITLE}](${PR_URL})"
            PR_LIST+=$'\n'
          done

          # Update the current PR description
          gh pr edit ${{ github.event.pull_request.number }} --body "$PR_LIST"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
